# Generated by Django 6.0.7 on 2026-07-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_morador_encomenda_reserva_veiculo_visitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
