# Generated by Django 6.0.7 on 2026-08-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sync_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Entregue', 'Entregue')], default='Pendente', max_length=15),
        ),
        migrations.AlterField(
            model_name='horariosfuncionamento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo_veiculo',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto'), ('Outro', 'Outro')], max_length=10),
        ),
    ]
